# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1300, 664)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("static/imgs/title.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(890, 90, 335, 503))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.input_2 = QtGui.QGroupBox(self.groupBox)
        self.input_2.setObjectName(_fromUtf8("input_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.input_2)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.w_aro = QtGui.QLineEdit(self.input_2)
        self.w_aro.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.w_aro.setObjectName(_fromUtf8("w_aro"))
        self.gridLayout_2.addWidget(self.w_aro, 2, 2, 1, 2)
        self.w_nitro = QtGui.QLineEdit(self.input_2)
        self.w_nitro.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.w_nitro.setObjectName(_fromUtf8("w_nitro"))
        self.gridLayout_2.addWidget(self.w_nitro, 1, 2, 1, 2)
        self.scrollArea = QtGui.QScrollArea(self.input_2)
        self.scrollArea.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 148, 103))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_3.addWidget(self.lineEdit_14, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 2, 1, 2)
        self.label_14 = QtGui.QLabel(self.input_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.input_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.input_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.input_2)
        self.input = QtGui.QGroupBox(self.groupBox)
        self.input.setObjectName(_fromUtf8("input"))
        self.gridLayout = QtGui.QGridLayout(self.input)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.input)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 2)
        self.r_oil = QtGui.QLineEdit(self.input)
        self.r_oil.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.r_oil.setObjectName(_fromUtf8("r_oil"))
        self.gridLayout.addWidget(self.r_oil, 7, 2, 1, 2)
        self.t_resid = QtGui.QLineEdit(self.input)
        self.t_resid.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.t_resid.setObjectName(_fromUtf8("t_resid"))
        self.gridLayout.addWidget(self.t_resid, 0, 2, 1, 2)
        self.label_8 = QtGui.QLabel(self.input)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.input)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.p = QtGui.QLineEdit(self.input)
        self.p.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.p.setObjectName(_fromUtf8("p"))
        self.gridLayout.addWidget(self.p, 1, 2, 1, 2)
        self.label_10 = QtGui.QLabel(self.input)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.input)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.t = QtGui.QLineEdit(self.input)
        self.t.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.t.setObjectName(_fromUtf8("t"))
        self.gridLayout.addWidget(self.t, 2, 2, 1, 2)
        self.label_11 = QtGui.QLabel(self.input)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.input)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.input)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 4, 1, 1)
        self.R = QtGui.QLineEdit(self.input)
        self.R.setStyleSheet(_fromUtf8("color:rgb(255, 73, 155);"))
        self.R.setObjectName(_fromUtf8("R"))
        self.gridLayout.addWidget(self.R, 4, 2, 1, 2)
        self.label = QtGui.QLabel(self.input)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.input)
        self.add = QtGui.QPushButton(self.groupBox)
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setObjectName(_fromUtf8("add"))
        self.verticalLayout.addWidget(self.add)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(610, 90, 241, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(890, 20, 331, 76))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.confirm_n = QtGui.QPushButton(self.groupBox_2)
        self.confirm_n.setAutoDefault(True)
        self.confirm_n.setDefault(False)
        self.confirm_n.setObjectName(_fromUtf8("confirm_n"))
        self.gridLayout_4.addWidget(self.confirm_n, 0, 1, 1, 1)
        self.n = QtGui.QSpinBox(self.groupBox_2)
        self.n.setObjectName(_fromUtf8("n"))
        self.gridLayout_4.addWidget(self.n, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1300, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "集总计算软件", None))
        self.input_2.setTitle(_translate("MainWindow", "原料性质", None))
        self.label_14.setText(_translate("MainWindow", "芳烃含量(<=1)", None))
        self.label_21.setText(_translate("MainWindow", "碱氮含量(<=1)", None))
        self.label_9.setText(_translate("MainWindow", "原料油组成(<=1)", None))
        self.input.setTitle(_translate("MainWindow", "反应条件", None))
        self.label_6.setText(_translate("MainWindow", "剂油比", None))
        self.label_8.setText(_translate("MainWindow", "s", None))
        self.label_3.setText(_translate("MainWindow", "反应压力", None))
        self.label_10.setText(_translate("MainWindow", "kPa", None))
        self.label_5.setText(_translate("MainWindow", "反应温度", None))
        self.label_11.setText(_translate("MainWindow", "K", None))
        self.label_4.setText(_translate("MainWindow", "R", None))
        self.label_12.setText(_translate("MainWindow", "J·mo1-1·k-1", None))
        self.R.setText(_translate("MainWindow", "8.3145", None))
        self.label.setText(_translate("MainWindow", "停留时间 ", None))
        self.add.setText(_translate("MainWindow", "添加", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "集总数", None))
        self.confirm_n.setText(_translate("MainWindow", "确认", None))
        self.menu.setTitle(_translate("MainWindow", "集总模型", None))

